Sort-of working version
puppetmaster Docker image starts up, with a generic host name.
Thereafter, "puppet agent -t" manages to certify alright, but is none
too happy with the name:

Info: Retrieving pluginfacts
Error: Could not retrieve pluginfacts: Parameter source failed on File[/var/lib/puppet/facts.d]: Could not understand source puppet://clusterforeman_puppetmaster_1.docker/pluginfacts: the scheme puppet does not accept registry part: clusterforeman_puppetmaster_1.docker (or bad hostname?)
Info: Retrieving plugin
Error: Could not retrieve plugin: Parameter source failed on File[/var/lib/puppet/lib]: Could not understand source puppet://clusterforeman_puppetmaster_1.docker/plugins: the scheme puppet does not accept registry part: clusterforeman_puppetmaster_1.docker (or bad hostname?)